# Comparison of Logistic Regression and Decision Tree

## Importing libraries and iris dataset

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.datasets import load_iris

iris=load_iris()

In [2]:
print (iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
print (iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [4]:
print (iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [5]:
print (iris.target_names)

['setosa' 'versicolor' 'virginica']


In [6]:
print (iris.data.shape)

(150, 4)


In [7]:
print (iris.target.shape)

(150,)


In [8]:
X=iris.data
y=iris.target
df_iris = pd.DataFrame(np.c_[iris['data'], iris['target']], columns = np.append(iris['feature_names'], ['target']))
df_iris.head(10)

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2     0.0
1                4.9               3.0  ...               0.2     0.0
2                4.7               3.2  ...               0.2     0.0
3                4.6               3.1  ...               0.2     0.0
4                5.0               3.6  ...               0.2     0.0
5                5.4               3.9  ...               0.4     0.0
6                4.6               3.4  ...               0.3     0.0
7                5.0               3.4  ...               0.2     0.0
8                4.4               2.9  ...               0.2     0.0
9                4.9               3.1  ...               0.1     0.0

[10 rows x 5 columns]

# Using Logistic Regression

## Classification on all features

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 4) (38, 4) (112,) (38,)


In [10]:
# implement using logistic regression
log_reg = LogisticRegression(random_state=123)
log_reg.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=123, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
y_predict = log_reg.predict(X_test)
y_predict

array([1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2])

In [12]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.79      0.88        14
           2       0.80      1.00      0.89        12

    accuracy                           0.92        38
   macro avg       0.93      0.93      0.92        38
weighted avg       0.94      0.92      0.92        38



In [13]:
print('Accuracy is',accuracy_score(y_predict,y_test))

Accuracy is 0.9210526315789473


## Calculating correlation matrix of dataset

In [14]:
df_iris.corr()

sepal length (cm)  ...    target
sepal length (cm)           1.000000  ...  0.782561
sepal width (cm)           -0.117570  ... -0.426658
petal length (cm)           0.871754  ...  0.949035
petal width (cm)            0.817941  ...  0.956547
target                      0.782561  ...  1.000000

[5 rows x 5 columns]

## Using high correlation features only
Since only sepal length, petal length and petal width have significantly more correlation with the target than sepal width, let's try classifying on only those three features

In [15]:
df_iris2 = df_iris.iloc[:, [0, 2, 3, 4]]
df_iris2.head()

sepal length (cm)  petal length (cm)  petal width (cm)  target
0                5.1                1.4               0.2     0.0
1                4.9                1.4               0.2     0.0
2                4.7                1.3               0.2     0.0
3                4.6                1.5               0.2     0.0
4                5.0                1.4               0.2     0.0

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df_iris2.iloc[:, :3].values, df_iris2.iloc[:, -1].values, test_size = 0.25, random_state = 5)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 3) (38, 3) (112,) (38,)


In [17]:
log_reg2 = LogisticRegression(random_state=123)
log_reg2.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=123, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
y_predict = log_reg2.predict(X_test)
y_predict

array([1., 2., 2., 0., 2., 1., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0., 2.,
       2., 0., 0., 1., 2., 0., 1., 1., 2., 1., 1., 1., 2., 0., 1., 1., 0.,
       1., 0., 0., 2.])

In [19]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        12
         1.0       1.00      0.79      0.88        14
         2.0       0.80      1.00      0.89        12

    accuracy                           0.92        38
   macro avg       0.93      0.93      0.92        38
weighted avg       0.94      0.92      0.92        38



In [20]:
print('Accuracy is',accuracy_score(y_predict,y_test))

Accuracy is 0.9210526315789473


## Using only petal length and petal width

In [21]:
df_iris3 = df_iris.iloc[:, [2, 3, 4]]
df_iris3.head()

petal length (cm)  petal width (cm)  target
0                1.4               0.2     0.0
1                1.4               0.2     0.0
2                1.3               0.2     0.0
3                1.5               0.2     0.0
4                1.4               0.2     0.0

In [22]:
X_train, X_test, y_train, y_test = train_test_split(df_iris3.iloc[:, :2].values, df_iris3.iloc[:, -1].values, test_size = 0.25, random_state = 5)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 2) (38, 2) (112,) (38,)


In [23]:
log_reg2 = LogisticRegression(random_state=123)
log_reg2.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=123, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [24]:
y_predict = log_reg2.predict(X_test)
y_predict

array([1., 1., 2., 0., 2., 1., 0., 2., 0., 2., 2., 1., 2., 2., 0., 0., 2.,
       2., 0., 0., 1., 2., 0., 2., 1., 2., 1., 1., 1., 2., 0., 1., 1., 0.,
       1., 0., 0., 2.])

In [25]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        12
         1.0       0.83      0.71      0.77        14
         2.0       0.71      0.83      0.77        12

    accuracy                           0.84        38
   macro avg       0.85      0.85      0.85        38
weighted avg       0.85      0.84      0.84        38



In [26]:
print('Accuracy is',accuracy_score(y_predict,y_test))

Accuracy is 0.8421052631578947


# Decision Tree

## Classification on all features

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 4) (38, 4) (112,) (38,)


In [28]:
tree1 = DecisionTreeClassifier(random_state=123)
tree1.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [29]:
y_predict = tree1.predict(X_test)
y_predict

array([1, 2, 2, 0, 2, 2, 0, 2, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2])

In [30]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.86      0.92        14
           2       0.86      1.00      0.92        12

    accuracy                           0.95        38
   macro avg       0.95      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38



In [31]:
print('Accuracy is',accuracy_score(y_predict,y_test))

Accuracy is 0.9473684210526315


## Using high correlation features only
Since only sepal length, petal length and petal width have significantly more correlation with the target than sepal width, let's try classifying on only those three features

In [32]:
df_iris2 = df_iris.iloc[:, [0, 2, 3, 4]]
df_iris2.head()

sepal length (cm)  petal length (cm)  petal width (cm)  target
0                5.1                1.4               0.2     0.0
1                4.9                1.4               0.2     0.0
2                4.7                1.3               0.2     0.0
3                4.6                1.5               0.2     0.0
4                5.0                1.4               0.2     0.0

In [33]:
X_train, X_test, y_train, y_test = train_test_split(df_iris2.iloc[:, :3].values, df_iris2.iloc[:, -1].values, test_size = 0.25, random_state = 5)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 3) (38, 3) (112,) (38,)


In [34]:
tree2 = DecisionTreeClassifier(random_state=123)
tree2.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [35]:
y_predict = tree2.predict(X_test)
y_predict

array([1., 2., 2., 0., 2., 2., 0., 2., 0., 1., 1., 2., 2., 2., 0., 0., 2.,
       2., 0., 0., 1., 2., 0., 1., 1., 2., 1., 1., 1., 2., 0., 1., 1., 0.,
       1., 0., 0., 2.])

In [36]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        12
         1.0       1.00      0.86      0.92        14
         2.0       0.86      1.00      0.92        12

    accuracy                           0.95        38
   macro avg       0.95      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38



In [37]:
print('Accuracy is',accuracy_score(y_predict,y_test))

Accuracy is 0.9473684210526315


## Using only petal length and petal width

In [38]:
df_iris3 = df_iris.iloc[:, [2, 3, 4]]
df_iris3.head()

petal length (cm)  petal width (cm)  target
0                1.4               0.2     0.0
1                1.4               0.2     0.0
2                1.3               0.2     0.0
3                1.5               0.2     0.0
4                1.4               0.2     0.0

In [39]:
X_train, X_test, y_train, y_test = train_test_split(df_iris3.iloc[:, :2].values, df_iris3.iloc[:, -1].values, test_size = 0.25, random_state = 5)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(112, 2) (38, 2) (112,) (38,)


In [40]:
tree3 = DecisionTreeClassifier(random_state=123)
tree3.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=123, splitter='best')

In [41]:
y_predict = tree3.predict(X_test)
y_predict

array([1., 2., 2., 0., 2., 1., 0., 2., 0., 1., 1., 2., 2., 2., 0., 0., 2.,
       2., 0., 0., 1., 2., 0., 1., 1., 2., 1., 1., 1., 2., 0., 1., 1., 0.,
       1., 0., 0., 2.])

In [42]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        12
         1.0       1.00      0.93      0.96        14
         2.0       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [43]:
print('Accuracy is',accuracy_score(y_predict,y_test))

Accuracy is 0.9736842105263158
